### ISSUE TITLE
Los atacantes deberían tener una función "me han dado" que baje la vida dependiendo de la fuerza de la torre

### ISSUE THREAD

**Issue by borjafdezgauna** [borjafdezgauna/DSG#2]

**Comment by aserrin55** [comment]
Hecho, falta por mejorar el momento en el que la torre comienza a disparar.

**Comment by aserrin55** [comment]
Ahora está hecho y la vida del atacante disminuye. La comprobación de que sigue vivo se realiza en el event tick del atacante, lo que habría que mejorar. También faltaría una animación de muerte antes de llamar al destroy actor.
