### ISSUE TITLE
Torretas de área

### ISSUE THREAD

**Issue by aserrin55** [borjafdezgauna/DSG#35]

**Comment by aserrin55** [comment]
Añadir animaciones.

**Comment by borjafdezgauna** [comment]
Y añadirlas al menú spawn units para que salgan. Hacen falta capturas

**Comment by borjafdezgauna** [comment]
Cada torre de área tiene dos variables de tipo ParticleSystem: una para el efecto que se hará sobre la torre y otra para el efecto sobre los atacantes afectados. Sólo hace falta editar los valores por defecto de cada clase y listo
