### ISSUE TITLE
Guardar estadísticas para mostrar al final de la partida

### ISSUE THREAD

**Issue by borjafdezgauna** [borjafdezgauna/DSG#43]
No estoy seguro de dónde se deberían de guardar... tdgamestate? playerstate?

**Comment by AsierEHU** [comment]
Voy a empezar guardando estadísticas en el gameState. Mostrarlas será otra tarea

**Comment by AsierEHU** [comment]
Listo, se podria mejorar el HUD pero lo dejo para más a delante
