### ISSUE TITLE
Aumentar el nivel de las torres y mejorar sus atributos.

### ISSUE THREAD

**Issue by aserrin55** [borjafdezgauna/DSG#49]
Las funciones creo que están hechas. Faltaría poner un botón en el hud de cada torre al hacer click y comprobar que funciona.

**Comment by aserrin55** [comment]
Falta hacerlo para las torretas de área y posteriormente que eneko lo incluya en el nuevo hud.

**Comment by borjafdezgauna** [comment]
esto está funcionando aunque faltan cosas estéticas: algún fx cuando se sube el nivel, que el nivel se vea en la descripción, etc...
