### ISSUE TITLE
Efecto de las balas

### ISSUE THREAD

**Issue by AsierEHU** [borjafdezgauna/DSG#57]
Que las balas se vean o solo el efecto al llegar o ambos.
Que las balas tengan que alcanzar al enemigo para dañarle:

- Calculando la posición del enemigo para cuando la bala llegue
- Haciendo balas muy muy rápidas.

Dejarlo todo como está.

**Comment by borjafdezgauna** [comment]
Creo que esto está solucionado... activé un flag dentro del componente de movimiento de las balas para que diesen siempre al objetivo. Creo que funciona no?

**Comment by aserrin55** [comment]
Sí, funciona

**Comment by borjafdezgauna** [comment]
Creo que ahora sí funciona... después de spawnear la bala se le asigna el homing target component (el atacante al que se ha disparado). En las pruebas todas las balas han dado al objetivo menos cuando alguien se pone en medio, pero eso creo que es normal
